### ISSUE TITLE
Socket.io P2P webcam RTC

### ISSUE THREAD

**Issue by brentguistwite** [brentguistwite/RRB-server#2]
- [x] [p2p socket io](https://socket.io/blog/socket-io-p2p/)
- [ ] Toggle camera on/off
- [ ] Toggle audio on/off
- [ ] Toggle Fullscreen

**Comment by YourWebDevGuy** [comment]
the three remaining checkboxes are a front-end thing not server-side. therefore I will ignore.
(this would be accomplished via webCam react component as the browser would be responsible for toggling full screen (css)).

Additionally, the react component would also have the button/switch to toggle on and off emitting the correct method to navigator.getUserMedia.
